#!/usr/bin/env bash

btrfs device add /dev/dev /Volumes/root -f
btrfs filesystem usage /Volumes/root -h -T
btrfs balance start -dconvert=raid1 -mconvert=raid1 -sconvert=raid1 /Volumes/root --full-balance --force --bg
btrfs filesystem usage /Volumes/root -h -T

# btrfs device remove /dev/nvme1n1p2 /Volumes/root
