#!/usr/bin/env bash

if [ -f "/srv/http/mashiro/os/aarch64/emacs-nox-mashiro-$(date "+%Y%m%d").1-aarch64.pkg.tar.zst" ]
  then
    echo "Nya"
  else
    cd /srv/http/mashiro/emacs-nox/ || exit
    makepkg

    rm /srv/http/mashiro/os/aarch64/emacs-nox*.pkg.tar.zst
    mv /srv/http/mashiro/emacs-nox/*.zst /srv/http/mashiro/os/aarch64/

    ssh mashiro@10.0.0.22 'rm /srv/http/mashiro/os/aarch64/emacs*.pkg.tar.zst'
    scp /srv/http/mashiro/os/aarch64/*.zst mashiro@10.0.0.22:/srv/http/mashiro/os/aarch64/

    rm -rf /srv/http/mashiro/emacs-nox/{pkg,src}
fi
