#!/usr/bin/env bash

if [ -f "/srv/http/mashiro/os/x86_64/emacs-mashiro-$(date "+%Y%m%d")-1-x86_64.pkg.tar.zst" ]; then
    echo "Nya"
  else
    rm /srv/http/mashiro/os/x86_64/emacs-mashiro*.pkg.tar.zst

    cd /srv/http/mashiro/emacs/ || exit
    makepkg

    mv /srv/http/mashiro/emacs/*.zst /srv/http/mashiro/os/x86_64/
    rm -rf /srv/http/mashiro/emacs/{pkg,src}
fi
