#!/usr/bin/env bash

if [ -f "/srv/http/mashiro/x86_64/emacs-pgtk-mashiro-$(date "+%Y%m%d")-1-x86_64.pkg.tar.zst" ]
  then
    echo "Nya"
  else
    rm /srv/http/mashiro/x86_64/emacs-pgtk*.pkg.tar.zst

    cd /srv/http/mashiro/emacs-pgtk/
    makepkg

    mv /srv/http/mashiro/emacs-pgtk/*.zst /srv/http/mashiro/x86_64/
    rm -rf /srv/http/mashiro/emacs-pgtk/pkg
    rm -rf /srv/http/mashiro/emacs-pgtk/src

    /srv/http/mashiro/UpdateRepo
fi
