#!/usr/bin/env bash

if [ -f "/srv/http/mashiro/os/x86_64/emacs-wayland-mashiro-$(date "+%Y%m%d")-1-x86_64.pkg.tar.zst" ]
  then
    echo "Nya"
  else
    rm /srv/http/mashiro/os/x86_64/emacs-wayland*.pkg.tar.zst

    cd /srv/http/mashiro/emacs-wayland/ || exit
    makepkg

    mv /srv/http/mashiro/emacs-wayland/*.zst /srv/http/mashiro/os/x86_64/
    rm -rf /srv/http/mashiro/emacs-wayland/pkg
    rm -rf /srv/http/mashiro/emacs-wayland/src

    /srv/http/mashiro/UpdateRepo
fi
