#!/usr/bin/env bash
rm /srv/http/mashiro/os/x86_64/linux-mainline*
cd /Users/mashiro/Library/Caches/linux-mainline
git pull
makepkg

mv /Users/mashiro/Library/Caches/linux-mainline*.zst /srv/http/mashiro/os/x86_64/
rm -rf /Users/mashiro/Library/Caches/linux-mainline/pkg
rm -rf /Users/mashiro/Library/Caches/linux-mainline/src

repo-add -n /srv/http/mashiro/os/x86_64/mashiro.db.tar.gz /srv/http/mashiro/os/x86_64/*.zst
