#!/usr/bin/env bash

Version=5.19.11-3
RC_AArch64=6.0.rc7-1
RPiMainlineVersion=5.19.11-1
RPiRCVersion=6.0.rc7-1
RC_x86_64=6.0.0rc7-1

cd /srv/http/mashiro/aarch64/
if [ -f "/srv/http/mashiro/aarch64/linux-$Version-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/aarch64/linux-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-$Version-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/aarch64/linux-rc-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/aarch64/linux-rpi4-mainline-$RPiMainlineVersion-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/aarch64/linux-rpi4-mainline-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rpi4-mainline-$RPiMainlineVersion-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/aarch64/linux-rpi4-rc-$RPiRCVersion-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/aarch64/linux-rpi4-rc-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rpi4-rc-$RPiRCVersion-aarch64.pkg.tar.zst
fi


cd /srv/http/mashiro/x86_64
if [ -f "/srv/http/mashiro/x86_64/linux60-$RC_x86_64-x86_64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/x86_64/linux60-*-x86_64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/unstable/core/x86_64/linux60-$RC_x86_64-x86_64.pkg.tar.zst
fi
