#!/usr/bin/env bash

RC_AArch64=6.3.rc5-1
RPiRCVersion=linux-rpi4-rc-6.3.rc7-1

x86_64=linux63-6.3.0rc7-1

cd /srv/http/mashiro/os/aarch64/

if [ -f "/srv/http/mashiro/os/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-rc-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/os/aarch64/$RPiRCVersion-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-rpi4-rc*.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/$RPiRCVersion-aarch64.pkg.tar.zst
fi

cd /srv/http/mashiro/os/x86_64
if [ -f "/srv/http/mashiro/os/x86_64/$x86_64-x86_64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/x86_64/linux*-x86_64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/unstable/core/x86_64/$x86_64-x86_64.pkg.tar.zst
fi

repo-add /srv/http/mashiro/os/aarch64/mashiro.db.tar.gz /srv/http/mashiro/os/aarch64/*.zst
repo-add /srv/http/mashiro/os/x86_64/mashiro.db.tar.gz /srv/http/mashiro/os/x86_64/*.zst
