#!/usr/bin/env bash

Version=6.0.1-1
RC_AArch64=6.0.rc7-2
RPiMainlineVersion=6.0.1-1
RPiRCVersion=linux-rpi4-rc-6.0.rc7-1

cd /srv/http/mashiro/os/aarch64/
if [ -f "/srv/http/mashiro/os/aarch64/linux-$Version-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-$Version-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/os/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-rc-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/os/aarch64/linux-rpi4-mainline-$RPiMainlineVersion-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-rpi4-mainline-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rpi4-mainline-$RPiMainlineVersion-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/os/aarch64/$RPiRCVersion-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/$RPiRCVersion.*.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/$RPiRCVersion-aarch64.pkg.tar.zst
fi
