#!/usr/bin/env bash

RC_AArch64=6.4.rc6-1
RPiRCVersion=linux-rpi4-rc-6.5.rc2-2

cd /srv/http/mashiro/os/aarch64/ || exit

if [ -f "/srv/http/mashiro/os/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-rc-*-aarch64.pkg.tar.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/linux-rc-$RC_AArch64-aarch64.pkg.tar.zst
fi
if [ -f "/srv/http/mashiro/os/aarch64/$RPiRCVersion-aarch64.pkg.tar.zst" ]
  then
      echo 'NyaNya'
  else
      rm /srv/http/mashiro/os/aarch64/linux-rpi4-rc*.zst
      curl -JLO https://mirrors.manjaro.org/repo/arm-unstable/core/aarch64/$RPiRCVersion-aarch64.pkg.tar.zst
fi
