#!/usr/bin/env bash

repo-add -n /srv/http/mashiro/os/aarch64/mashiro.db.tar.gz /srv/http/mashiro/os/aarch64/*.zst
repo-add -n /srv/http/mashiro/os/x86_64/mashiro.db.tar.gz /srv/http/mashiro/os/x86_64/*.zst
