#!/usr/bin/env bash

/srv/http/mashiro/OpenWrt/mediatek-filogic
/srv/http/mashiro/OpenWrt/ramips-mt7620
/srv/http/mashiro/OpenWrt/ramips-mt7621
/srv/http/mashiro/OpenWrt/ramips-mt76x8
/srv/http/mashiro/OpenWrt/rockchip-armv8
