#!/usr/bin/env bash

cd /srv/http/emacs.git && git fetch
rm -rf /srv/http/emacs && git clone /srv/http/emacs.git /srv/http/emacs
cd /srv/http/emacs
/srv/http/emacs/autogen.sh
/srv/http/emacs/configure --without-compress-install --with-mailutils --with-native-compilation --with-sound=alsa

make -j20

cd /srv/http/org-mode.git && git fetch
rm -rf /srv/http/org-mode && git clone /srv/http/org-mode.git /srv/http/org-mode
cd /srv/http/org-mode
make autoloads -j20

cd /srv/http/org-contrib.git && git fetch
rm -rf /srv/http/org-contrib && git clone /srv/http/org-contrib.git /srv/http/org-contrib

rm -rf /Users/mashiro/Library/Caches/emacs/straight
