#!/usr/bin/env bash

rm /srv/http/mashiro/os/x86_64/linux-mainline*
cd /Users/mashiro/Library/Caches/ || exit
git clone https://aur.archlinux.org/linux-mainline
cd /Users/mashiro/Library/Caches/linux-mainline || exit
git -C /Users/mashiro/Library/Caches/linux-mainline pull
makepkg

mv /Users/mashiro/Library/Caches/linux-mainline/*.zst /srv/http/mashiro/os/x86_64/
rm -rf /Users/mashiro/Library/Caches/linux-mainline/{pkg,src}
