#!/usr/bin/env bash

Target=bcm27xx
Arch=bcm2712

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make image PROFILE=rpi-5 PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-igc kmod-mac80211 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode pciutils usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
