#!/usr/bin/env bash

Target=bcm27xx
Arch=bcm2710

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=rpi-3 ROOTFS_PARTSIZE="2048" PACKAGES="apk-openssl auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk coreutils-cat coreutils-dd coreutils-ls curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-mac80211 kmod-fs-nfs-v4 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas lsd luci luci-app-irqbalance luci-ssl-openssl nano-full nfs-kernel-server-utils nfs-utils openssh-sftp-avahi-service pciutils rsync usbutils wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
