#!/usr/bin/env bash

Target=bcm27xx
Arch=bcm2708

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xfopenwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make -j$(nproc) image PROFILE=rpi PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk cifsmount curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-fs-nfs-v4 kmod-usb-net-cdc-subset kmod-usb-net-rtl8152 kmod-usb-storage-extras kmod-usb-storage-uas ksmbd-avahi-service lsd luci luci-app-attendedsysupgrade luci-app-irqbalance luci-app-ksmbd luci-proto-wireguard luci-ssl-openssl nano-full nfs-kernel-server-utils nfs-utils openssh-sftp-avahi-service qrencode rsync usbutils wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
