#!/usr/bin/env bash

Target=bcm53xx
Arch=generic

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make -j$(nproc) image PROFILE=asus_rt-ac88u PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk cifsmount curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-fs-nfs-v4 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas ksmbd-avahi-service lsd luci luci-app-attendedsysupgrade luci-app-ksmbd luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full nfs-kernel-server-utils nfs-utils openssh-sftp-avahi-service qrencode rsync usbip-client usbip-server usbutils wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
