#!/usr/bin/env bash

Target=mediatek
Arch=filogic

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=bananapi_bpi-r3 PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full luci-app-irqbalance luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=bananapi_bpi-r3-mini PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full kmod-mtd-rw luci-app-irqbalance luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=bananapi_bpi-r4 PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop hwclock ip-full iw-full luci-app-irqbalance luci-app-package-manager luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=glinet_gl-mt3000 PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=glinet_gl-mt6000 PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full luci-app-irqbalance luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=openwrt_one PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full kmod-mtd-rw luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=xiaomi_mi-router-ax3000t-ubootmod PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full kmod-mtd-rw luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=xiaomi_redmi-router-ax6000-ubootmod PACKAGES="apk-openssl avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd dmesg dnsmasq-full htop ip-full iw-full kmod-mtd-rw luci-app-irqbalance luci-app-package-manager luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wget-ssl wpad-openssl -apk-mbedtls -dnsmasq -libustream-mbedtls -odhcpd-ipv6only -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
