#!/usr/bin/env bash

Target=mediatek
Arch=filogic

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make image PROFILE=bananapi_bpi-r3-mini
make image PROFILE=bananapi_bpi-r3 PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-nvme kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full nvme-cli openssh-sftp-server pciutils usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=bananapi_bpi-r4 PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-nvme kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full nvme-cli openssh-sftp-server pciutils usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=glinet_gl-mt3000 PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=glinet_gl-mt6000 PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=xiaomi_mi-router-ax3000t-ubootmod PACKAGES="dnsmasq-full ip-full iw-full luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=xiaomi_mi-router-wr30u-ubootmod PACKAGES="dnsmasq-full ip-full iw-full luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=xiaomi_redmi-router-ax6000-ubootmod PACKAGES="dnsmasq-full ip-full iw-full luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
