#!/usr/bin/env bash

Target=ramips
Arch=mt7621

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make image PROFILE=totolink_x5000r PACKAGES="dnsmasq-full ip-full iw-full luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make image PROFILE=xiaomi_mi-router-3g PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-usteer luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
