#!/usr/bin/env bash

Target=ramips
Arch=mt7621

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=openfi_5pro PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk coreutils-cat coreutils-ls dmesg dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas lsd luci-app-irqbalance luci-app-opkg luci-proto-qmi luci-ssl-openssl nano-full openssh-sftp-avahi-service owut rsync usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=xiaomi_mi-router-3g PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk coreutils-cat coreutils-ls dmesg dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas lsd luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut rsync usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch -wpad-basic-mbedtls"
