#!/usr/bin/env bash

Target=ramips
Arch=mt7620

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make -j$(nproc) image PROFILE=hiwifi_hc5761 PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh blockd cifsmount curl dnsmasq-full ip-full iw-full kmod-fs-btrfs kmod-fs-msdos kmod-fs-nfs-v4 kmod-usb-net-cdc-subset kmod-usb-storage-extras luci luci-app-attendedsysupgrade luci-proto-wireguard luci-ssl-openssl nano-full nfs-utils openssh-sftp-avahi-service qrencode wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=hiwifi_hc5861 PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh blockd cifsmount curl dnsmasq-full ip-full iw-full kmod-fs-btrfs kmod-fs-msdos kmod-fs-nfs-v4 kmod-usb-net-cdc-subset kmod-usb-storage-extras luci luci-app-attendedsysupgrade luci-proto-wireguard luci-ssl-openssl nano-full nfs-utils openssh-sftp-avahi-service qrencode wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
