#!/usr/bin/env bash

Target=ramips
Arch=mt7620

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=hiwifi_hc5761 PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-ls curl dmesg dnsmasq-full ip-full iw-full kmod-fs-btrfs kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras lsd luci luci-ssl-openssl nano-full openssh-sftp-avahi-service rsync usbutils wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=hiwifi_hc5861 PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-ls curl dmesg dnsmasq-full ip-full iw-full kmod-fs-btrfs kmod-fs-msdos kmod-usb-net-cdc-subset kmod-usb-storage-extras lsd luci luci-ssl-openssl nano-full openssh-sftp-avahi-service rsync usbutils wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -wpad-basic-mbedtls"
