#!/usr/bin/env bash

Target=rockchip
Arch=armv8

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

make -j$(nproc) image PROFILE=friendlyarm_nanopi-r4s PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-mac80211 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-irqbalance luci-app-usteer luci-compat luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r5c PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-mac80211 kmod-mt7921e kmod-mt7922-firmware kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-irqbalance luci-app-usteer luci-compat luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server pciutils usbutils wpad-openssl -dnsmasq -kmod-rtw88-8822ce -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -rtl8822ce-firmware -wpad-basic-mbedtls"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r5s PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-mac80211 kmod-mt7921e kmod-nvme kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-irqbalance luci-app-usteer luci-compat luci-proto-wireguard luci-ssl-openssl nano-full nvme-cli openssh-sftp-server pciutils usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r6s PACKAGES="blockd btrfs-progs cfdisk curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-mac80211 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas luci luci-app-irqbalance luci-app-usteer luci-compat luci-proto-wireguard luci-ssl-openssl nano-full openssh-sftp-server qrencode usbutils wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe"
