#!/usr/bin/env bash

Target=rockchip
Arch=armv8

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=friendlyarm_nanopi-r4s PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-dd coreutils-ls dmesg dnsmasq-full htop ip-full iw-full kmod-nft-tproxy lsd luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut sing-box wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r5c PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-date coreutils-dd coreutils-ls dmesg dnsmasq-full htop hwclock ip-full iw-full kmod-nft-tproxy kmod-mac80211 kmod-mt7921e kmod-mt7922-firmware kmod-nft-tproxy lsd luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut sing-box wpad-openssl -dnsmasq -kmod-rtw88-8822ce -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe -rtl8822ce-firmware -wpad-basic-mbedtls" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r5s PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-date coreutils-dd coreutils-ls dmesg dnsmasq-full htop hwclock ip-full iw-full kmod-mac80211 kmod-mt7921e kmod-nft-tproxy lsd luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut sing-box wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r6s PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-dd coreutils-ls dmesg dnsmasq-full htop ip-full iw-full kmod-nft-tproxy lsd luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut sing-box wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch" ROOTFS_PARTSIZE="2048"
