#!/usr/bin/env bash

Target=x86
Arch=64

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=generic ROOTFS_PARTSIZE="2048" PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-dd coreutils-ls dmesg dnsmasq-full grep ip-full iw-full kmod-mac80211 lsd luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -opkg -ppp -ppp-mod-pppoe -uclient-fetch"
