#!/usr/bin/env bash

Target=x86
Arch=64

cd /srv/http/OpenWrt/ImageBuilder || exit
rm -rf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.openwrt.org/snapshots/targets/$Target/$Arch/openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm openwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd openwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .
ln -s ../dl .

make -j$(nproc) image PROFILE=generic ROOTFS_PARTSIZE="2048" PACKAGES="auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk cifsmount coreutils-cat coreutils-dd coreutils-ls curl dnsmasq-full dosfstools fdisk ip-full iw-full kmod-fs-msdos kmod-fs-nfs-v4 kmod-nvme kmod-mac80211 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas ksmbd-avahi-service lsd luci luci-app-attendedsysupgrade luci-app-irqbalance luci-app-ksmbd luci-proto-wireguard luci-ssl-openssl nano-full nfs-kernel-server-utils nfs-utils nvme-cli openssh-sftp-avahi-service pciutils qrencode rsync usbutils wget-ssl wpad-openssl -dnsmasq -libustream-mbedtls -odhcp6c -odhcpd-ipv6only -ppp -ppp-mod-pppoe"
