#!/usr/bin/env bash

Target=mediatek
Arch=filogic

cd /srv/http/ImmortalWrt/ImageBuilder || exit
rm -rf immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.immortalwrt.org/snapshots/targets/$Target/$Arch/immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
tar xf immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
rm immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.xz
cd immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .
ln -s ../dl .
