#!/usr/bin/env bash

Target=rockchip
Arch=armv8

cd /srv/http/ImmortalWrt/ImageBuilder || exit
rm -rf immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.immortalwrt.org/snapshots/targets/$Target/$Arch/immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=friendlyarm_nanopi-r6s PACKAGES="apk-openssl auc avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd btrfs-progs cfdisk coreutils-cat coreutils-dd coreutils-ls curl dosfstools ip-full kmod-fs-msdos kmod-fs-nfs-v4 kmod-usb-net-cdc-subset kmod-usb-storage-extras kmod-usb-storage-uas lsd luci luci-app-3ginfo-lite luci-app-attendedsysupgrade luci-app-dae luci-app-daed luci-app-homeproxy luci-app-irqbalance luci-app-v2raya luci-proto-modemmanager luci-proto-qmi luci-proto-wireguard luci-ssl-openssl nano-full nfs-kernel-server-utils nfs-utils openssh-sftp-avahi-service qrencode rsync usbutils v2ray-core wget-ssl -automount -ppp-mod-pppoe" ROOTFS_PARTSIZE="2048"
