#!/usr/bin/env bash

Target=rockchip
Arch=armv8

cd /srv/http/ImmortalWrt/ImageBuilder || exit
rm -rf immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64
curl -JLO https://downloads.immortalwrt.org/snapshots/targets/$Target/$Arch/immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
tar --use-compress-program=unzstd -xf immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
rm immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64.tar.zst
cd immortalwrt-imagebuilder-$Target-$Arch.Linux-x86_64 || exit

ln -s ../bin .

make -j$(nproc) image PROFILE=friendlyarm_nanopi-r5s PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-dd coreutils-ls ip-full lsd luci-compat luci-app-daed luci-app-irqbalance luci-app-opkg luci-ssl-openssl nano-full openssh-sftp-avahi-service owut -automount -ipv6helper -opkg -ppp -ppp-mod-pppoe -uclient-fetch" ROOTFS_PARTSIZE="2048"
make -j$(nproc) image PROFILE=friendlyarm_nanopi-r6s PACKAGES="avahi-daemon-service-http avahi-daemon-service-ssh avahi-dbus-daemon blockd coreutils-cat coreutils-dd coreutils-ls ip-full lsd luci-compat luci-app-daed luci-app-irqbalance luci-app-opkg luci-app-vlmcsd luci-ssl-openssl nano-full openssh-sftp-avahi-service owut -automount -ipv6helper -opkg -ppp -ppp-mod-pppoe -uclient-fetch" ROOTFS_PARTSIZE="2048"
